### PR TITLE
Prepare recipe for NWPD integration

### PR DESCRIPTION
**Pull request by BerkieBb**
Has been tested, works but the formatting of the config.json is just a little fucked up after because I wasn't able to find how to fix that.

### CODE REVIEW

**Review by ARSSANTO — COMMENTED** [review]
@BerkieBb  qb-npwd or qbx-npwd ?

**Comment by BerkieBb** [comment]
qbx, you can see that in the changelog on the discord

**Comment by BerkieBb** [comment]
Or just follow the link

**Review by Manason — APPROVED** [review]

**Comment by BerkieBb** [comment]
I got what you meant with that now @ARSSANTO

**Comment by BerkieBb** [comment]
The link you provided did not lead me to that text lol

**Comment by ARSSANTO** [comment]
Yeah i didnt notice that sorry

**Pull request closed without merging**
