### PR TITLE
Added ox:userLocales convar

### PR DESCRIPTION
**Pull request by mataskc**
## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Comment by Manason** [comment]
I imagine most servers would not want this feature turned on.

**Comment by mataskc** [comment]
This Feature is enabled by default. When set to '0', it is deactivated

**Comment by Manason** [comment]
> This Feature is enabled by default. When set to '0', it is deactivated

Oh. Maybe we should ship with it disabled then.

**Comment by mataskc** [comment]
Changed it to 0

**Pull request merged**
